# Generated by Django 5.2.7 on 2026-03-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('address', models.CharField(max_length=500, verbose_name='Manzili')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Xona raqami')),
                ('floor', models.IntegerField(verbose_name='Qavat')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maydoni (kv.m)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Narxi')),
                ('capacity', models.IntegerField(verbose_name="Odam sig'imi")),
                ('description', models.TextField(blank=True, verbose_name="Xona haqida ma'lumot")),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR kod')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.businesscenter', verbose_name='Biznes Markaz')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.officeroom')),
            ],
        ),
    ]
