# Generated by Django 5.2.7 on 2026-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businesscenter_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeroom',
            name='assigned_to',
            field=models.CharField(blank=True, help_text="Agar status 'Occupied' bo'lsa, mijoz ismini kiriting", max_length=255, null=True, verbose_name='Kimga ijaraga berilgan'),
        ),
        migrations.AddField(
            model_name='officeroom',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='officeroom',
            name='floor',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Qavat (masalan: 1, 1.5, 2)'),
        ),
    ]
