# Generated by Django 5.2.7 on 2026-03-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_officeroom_assigned_to_officeroom_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscenter',
            name='map_link',
            field=models.URLField(blank=True, help_text='Masalan: https://yandex.uz/maps/...', max_length=1000, null=True, verbose_name='Xarita havolasi (Google/Yandex)'),
        ),
    ]
