# Generated by Django 5.2.7 on 2026-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_businesscenter_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscenter',
            name='total_floors',
            field=models.IntegerField(default=1, verbose_name='Qavatlar soni'),
        ),
    ]
