# Generated by Django 5.2.7 on 2026-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businesscenter_total_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscenter',
            name='admin_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Admin Username'),
        ),
    ]
