# Generated by Django 5.2.7 on 2026-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_businesscenter_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscenter',
            name='building_image',
            field=models.ImageField(blank=True, null=True, upload_to='center_images/', verbose_name='Bino Rasmi'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='center_logos/', verbose_name='Markaz Logotipi'),
        ),
    ]
