# Generated by Django 5.2.7 on 2026-03-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_businesscenter_building_image_businesscenter_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeroom',
            name='price_period',
            field=models.CharField(choices=[('HOURLY', 'Soatlik'), ('DAILY', 'Kunlik'), ('MONTHLY', 'Oylik')], default='MONTHLY', max_length=20, verbose_name='Narx muddati'),
        ),
    ]
