# Generated by Django 5.2.7 on 2026-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_officeroom_price_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscenter',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='center_qr_codes/', verbose_name='QR kod'),
        ),
    ]
