# Generated by Django 5.2.7 on 2026-04-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_businesscenter_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xona turi nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='core.businesscenter', verbose_name='Biznes Markaz')),
            ],
        ),
        migrations.AddField(
            model_name='officeroom',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core.roomtype', verbose_name='Xona turi'),
        ),
    ]
