# Generated by Django 5.2.7 on 2026-04-05 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_roomtype_officeroom_room_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscenter',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='businesscenter',
            name='admin_username',
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='managed_centers', to=settings.AUTH_USER_MODEL, verbose_name='Markaz Adminlari'),
        ),
    ]
