# Generated by Django 5.2.7 on 2026-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeroom',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Narxi'),
        ),
    ]
