# Generated by Django 5.2.7 on 2026-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_officeroom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscenter',
            name='access_control',
            field=models.BooleanField(default=False, verbose_name='Kirishni nazorat qilish (Access Control)'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='building_class',
            field=models.CharField(blank=True, choices=[('A', 'Class A (Eng yuqori)'), ('B+', 'Class B+'), ('B', 'Class B'), ('C', 'Class C')], max_length=2, null=True, verbose_name='Bino sinfi'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='elevator_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Liftlar soni'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_backup_power',
            field=models.BooleanField(default=False, verbose_name='Zaxira elektr quvvati (Generator)'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_chill_zone',
            field=models.BooleanField(default=False, verbose_name='Chill Zone (Dam olish)'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_coffee_zone',
            field=models.BooleanField(default=False, verbose_name='Kofe zonasi'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_conference_hall',
            field=models.BooleanField(default=False, verbose_name='Konferensiya zali'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_kitchen',
            field=models.BooleanField(default=False, verbose_name='Oshxona'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_lounge',
            field=models.BooleanField(default=False, verbose_name='Lounge oromgoxi'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_meeting_rooms',
            field=models.BooleanField(default=False, verbose_name='Majlislar xonasi'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Avtoturargoh mavjudmi'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_reception',
            field=models.BooleanField(default=False, verbose_name='Qabulxona (Reception)'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_terrace',
            field=models.BooleanField(default=False, verbose_name='Terrasa'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='heating_cooling',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Isitish/Sovutish tizimi'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram (@username yoki havola)'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='internet_providers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Internet provayderlari'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='parking_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Avtoturargoh sig'imi"),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='security_24_7',
            field=models.BooleanField(default=False, verbose_name='24/7 Xavfsizlik'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram (@username yoki havola)'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='total_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Umumiy maydoni (kv.m)'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Veb-sayt'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Masalan: Dush-Juma, 09:00-18:00 YOKI 24/7', max_length=255, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='businesscenter',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qurilgan yili'),
        ),
    ]
